-- Tabela de vendedores sincronizada com SprintHub
CREATE TABLE IF NOT EXISTS vendedores (
  id INT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  cpf VARCHAR(14) NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  birthDate DATE NOT NULL,
  telephone VARCHAR(20) NULL,
  photo TEXT NULL,
  admin TINYINT DEFAULT 0,
  branch VARCHAR(100) NULL,
  position_company VARCHAR(255) NULL,
  skills TEXT NULL,
  state VARCHAR(100) NULL,
  city VARCHAR(100) NULL,
  whatsapp_automation VARCHAR(20) NULL,
  last_login DATETIME NULL,
  last_action DATETIME NULL,
  status ENUM('active', 'inactive', 'blocked') DEFAULT 'active',
  synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_email (email),
  INDEX idx_username (username),
  INDEX idx_status (status),
  INDEX idx_synced_at (synced_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
