-- Tabela de oportunidades sincronizadas do SprintHub
CREATE TABLE IF NOT EXISTS `oportunidades` (
  `id` bigint UNSIGNED NOT NULL,
  `title` varchar(255) NOT NULL,
  `value` decimal(15,2) DEFAULT '0.00',
  `crm_column` varchar(100) DEFAULT NULL,
  `lead_id` bigint UNSIGNED DEFAULT NULL,
  `sequence` int DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `loss_reason` varchar(255) DEFAULT NULL,
  `gain_reason` varchar(255) DEFAULT NULL,
  `expectedCloseDate` date DEFAULT NULL,
  `sale_channel` varchar(100) DEFAULT NULL,
  `campaign` varchar(100) DEFAULT NULL,
  `user` varchar(100) DEFAULT NULL,
  `last_column_change` datetime DEFAULT NULL,
  `last_status_change` datetime DEFAULT NULL,
  `gain_date` datetime DEFAULT NULL,
  `lost_date` datetime DEFAULT NULL,
  `reopen_date` datetime DEFAULT NULL,
  `await_column_approved` tinyint(1) DEFAULT '0',
  `await_column_approved_user` varchar(100) DEFAULT NULL,
  `reject_appro` tinyint(1) DEFAULT '0',
  `reject_appro_desc` varchar(255) DEFAULT NULL,
  `conf_installment` json DEFAULT NULL,
  `fields` json DEFAULT NULL,
  `createDate` datetime DEFAULT NULL,
  `updateDate` datetime DEFAULT NULL,
  `archived` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `coluna_funil_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_lead_id` (`lead_id`),
  KEY `idx_coluna_funil_id` (`coluna_funil_id`),
  KEY `idx_user` (`user`),
  KEY `idx_createDate` (`createDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

